version: '3.8'
services:
    mysqldb:
        container_name: mysqldb
        image: mysql:5.7
        restart: always
        volumes:
          - db_data:/var/lib/mysql
          - ./conf/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
            MYSQL_DATABASE: "ecomdb"
            MYSQL_USER: "ecomuser"
            MYSQL_PASSWORD: "ecompassword"
        ports:
            - "3307:3306"

    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - mysqldb
        ports:
            - 90:80
volumes:
  db_data:
